### ISSUE TITLE
Make the ringbuffer log to the kernel ringbuffer until the node is ready

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zinit#17]
Right now, we get logging of the booting kernel, and then the zinit ringbuffer takes over, not logging to the console. if there are problems, we can't see anything and the node stays in a state where we can't know what really happened.

there are a few solutions to it, but either way, we'll need to be able to get a node in rescue mode, or to be able that we can get to all logging up to the moment the node gets into the ready state.

so : 
- a `rescue` boot parameter ?
- split the networkd bootstrap code in one part to get the network going and the log to a remote from the zinit ringbuffer ?
- have a `noservice $string` to get the node to boot without the specific service ? ( but that would require that the whole graph **after** the service needs to be disabled too...
- any ideas ? (I love the 2nd idea)

**Comment by muhamadazmy** [comment]
- We already have a terminal running on tty2. This should be taken out before the production release.
- ringbuffer is configurable per service, so you can specify in a service config if u want to opt out of a ringbuffer, hence the logs will go console instead (not kernel buffer), so it will only be available on screen.
- skipping a service can be done, and by default all depending services will get blocked as well.

**Comment by sasha-astiadi** [comment]
obsolete issue. closing.
