### ISSUE TITLE
wait for oneshot service to finish in the after list

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/zinit#3]
Given 2 services like
init.yaml:
```yaml
exec: /bin/init
oneshot: true
```

foo.yaml
```yaml
exec: /bin/foo
after:
 - init
```

Currently foo will start as soon as init as been started. But if init takes some time to execute, foo can be started before init is done which is not the expected behavior since you ask to run after init and init is a oneshot.
So I think when a dependency has the oneshot: true, zinit should wait for it to done before starting the dependent services

**Comment by muhamadazmy** [comment]
Fixed https://github.com/threefoldtech/zinit/commit/b814011e678454dfad6a58d120a464a75f1892ee
