### ISSUE TITLE
zinit log sub-command should fail explicitly when used with unknown service

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/zinit#44]
when you have a typo in a service name or use a service that is not registered with zinit with a command like `status` or `stop`  it gives a clear error
```sh
zinit status foo
service name "foo" unknow
```
however, with `log` command it will be hanging there with no output. this could mislead the user into thinking that the process can't progress as it does not create logs.

```sh
zinit log foo
```

I expected the `log` command to fail with a similar error as above when used with an unknown service name.

it happens to me personally, when I made a typo in a service name and went thinking that the service stuck for some reason which wasn't correct.

**Comment by muhamadazmy** [comment]
fixed in https://github.com/threefoldtech/zinit/releases/tag/v0.2.11
