### ISSUE TITLE
zinit problem on alpine

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/zinit#50]
it prints out an error:
```
zinit: ERROR (zinit::manager) failed to load /etc/environment file: No such file or directory (os error 2
```
It does continue afterwards so it's not blocking but it does not load the environment off course

**Comment by muhamadazmy** [comment]
I will change that to print a nice `info` that the env file is going to be skipped

**Comment by muhamadazmy** [comment]
Fixed by https://github.com/threefoldtech/zinit/commit/6edf2c585b3814edcf3faf6862a4d5a5dd563e01

(not released yet)
