### ISSUE TITLE
Zinit doesn't bring the loopback interface up

### ISSUE THREAD

**Issue by delandtj** [threefoldtech/zinit#8]
`ip link set lo up` : no need to add an IPv{4,6} as the kernel does that automatically.

**Comment by zaibon** [comment]
I don't think zinit itself does anything with the network.
We might need to add some init script to do so though, but I think we can tackle this in https://github.com/threefoldtech/zosv2/issues/44

**Comment by delandtj** [comment]
Meh... stoopit me... of course it's networkd that needs to do that
